imports:
    - { resource: "@PartFireSlackBundle/Resources/config/services.yml" }

services:
    partfire_common.repo:
        class: PartFire\CommonBundle\Entity\Repository\RepositoryFactory
        arguments: ['@doctrine.orm.default_entity_manager']

    partfire_common.country_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PartFire\CommonBundle\Entity\Country

    partfire_common.output_burn:
        class: PartFire\CommonBundle\Services\Output\Cli\BurnOutput

    partfire_common.output_console:
        class: PartFire\CommonBundle\Services\Output\Cli\ConsoleOutput

    partfire_common.time_ago:
        class: PartFire\CommonBundle\Services\DateTime\TimeAgo

    partfire_common.date_time_service:
        class: PartFire\CommonBundle\Services\DateTime\DateTimeService
        arguments: ['@partfire_common.time_ago']

    partfire_common.new_user_events_service:
        class: PartFire\CommonBundle\EventListener\NewUserListener
        arguments: ['@partfire_common.repo']
        tags:
              - { name: kernel.event_listener, event: fos_user.registration.completed, method: onCreateUserSetIPAddress }

    partfire_common.csv_service:
        class: PartFire\CommonBundle\Services\CSV\CSVService
